<?php

declare(strict_types=1);

namespace C14r\Directus\API;

final class Errors
{
    const INTERNAL_ERROR = 0;
    const NOT_FOUND = 1;
    const BAD_REQUEST = 2;
    const UNAUTHORIZED = 3;
    const INVALID_REQUEST = 4;
    const ENDPOINT_NOT_FOUND = 5;
    const METHOD_NOT_ALLOWED = 6;
    const TOO_MANY_REQUESTS = 7;
    const PROJECT_CONFIG_NOT_FOUND = 8;
    const FAILED_SQL_QUERY = 9;
    const FORBIDDEN = 10;
    const CONNECTING_TO_THE_DATABASE = 11;
    const UNPROCESSABLE_ENTITY = 12;
    const INVALID_PAYLOAD = 13;
    const DEFAULT_PROJECT_NOT_CONFIGURED = 14;
    const BATCH_UPLOAD_NOT_ALLOWED = 15;
    const INVALID_FILESYSTEM_PATH = 16;
    const INVALID_CONFIG_PATH = 17;
    const PROJECT_NAME_ALREADY_EXISTS = 18;
    const UNAUTHORIZED_LOCATION_ACCESS = 18;
    const INSTALLATION_INVALID_DATABASE = 19;
    const MISSING_STORAGE_CONFIG = 20;
    const CURRENTLY_UNDER_MAINTENANCE = 21;
    const INVALID_CACHE_ADAPTER = 22;
    const INVALID_CACHE_CONFIG = 23;
    const UNKNOWN_PROJECT = 24;

    const AUTH_INVALID_CREDENTIALS = 100;
    const AUTH_INVALID_TOKEN = 101;
    const AUTH_EXPIRED_TOKEN = 102;
    const AUTH_INACTIVE_USER = 103;
    const AUTH_INVALID_RESET_TOKEN = 104;
    const AUTH_EXPIRED_RESET_TOKEN = 105;
    const AUTH_USER_NOT_FOUND = 106;
    const AUTH_USER_WITH_EMAIL_NOT_FOUND = 107;
    const AUTH_USER_NOT_AUTHENTICATED = 108;
    const AUTH_INVALID_REQUEST_TOKEN = 109;
    const AUTH_EXPIRED_REQUEST_TOKEN = 110;
    const AUTH_USER_MISSING_2FA_OTP = 111;
    const AUTH_INVALID_USER_OTP = 112;
    const AUTH_2FA_ENFORCED_BUT_NOT_ACTIVATED = 113;
    const AUTH_VALIDATION_ERROR = 114;
    const AUTH_SSO_NOT_ALLOWED_WITH_2FA_ENABLED = 115;

    const ITEMS_COLLECTION_NOT_FOUND = 200;
    const ITEMS_NOT_ALLOW_DIRECT_ACCESS_TO_SYSTEM_TABLE = 201;
    const ITEMS_FIELD_NOT_FOUND = 202;
    const ITEM_NOT_FOUND = 203;
    const ITEM_DUPLICATED = 204;
    const ITEMS_COLLECTION_NOT_MANAGED_BY_DIRECTUS = 205;
    const ITEMS_FIELD_NOT_MANAGED_BY_DIRECTUS = 206;
    const ITEMS_REVISION_NOT_FOUND = 207;
    const ITEMS_REVISION_HAS_INVALID_DELTA = 208;
    const ITEMS_FIELD_INVALID = 209;
    const ITEMS_CAN_NOT_CREATE_COMMENT_FOR_ITEM = 210;
    const ITEMS_CAN_NOT_UPDATE_COMMENT_FOR_ITEM = 211;
    const ITEMS_CAN_NOT_DELETE_COMMENT_FROM_ITEM = 212;
    const ITEMS_FIELD_DOES_NOT_ALLOWED_VALUE = 213;
    const ITEMS_UNKNOWN_FILTER = 214;
    const ITEMS_UNABLE_TO_ACCESS_DATA_FROM_A_RELATED_COLLECTION = 215;
    const ITEMS_DELETE_LAST_ADMIN_IS_FORBIDDEN = 216;

    const COLLECTIONS_READING_ITEMS_DENIED = 300;
    const COLLECTIONS_CREATING_ITEMS_DENIED = 301;
    const COLLECTIONS_UPDATING_ITEMS_DENIED = 302;
    const COLLECTIONS_DELETING_ITEMS_DENIED = 303;
    const COLLECTIONS_READING_FIELD_DENIED = 304;
    const COLLECTIONS_UPDATING_FIELD_DENIED = 305;
    const COLLECTIONS_ALTERING_COLLECTION_DENIED = 306;
    // 0305 ?
    const COLLECTIONS_COLLECTION_ALREADY_EXISTS = 307;
    const COLLECTIONS_FIELD_ALREADY_EXISTS = 308;
    const COLLECTIONS_UNABLE_TO_FIND_ITEMS_OWNED_BY_USER = 309;

    const SCHEMA_UNKNOWN_ERROR = 400;
    const SCHEMA_UNKNOWN_DATA_TYPE = 401;
    const SCHEMA_FIELD_TYPE_MISSING_LENGTH = 402;
    const SCHEMA_FIELD_TYPE_DO_NOT_SUPPORT_LENGTH = 403;
    const SCHEMA_UNABLE_TO_MAKE_FIELD_REQUIRED = 404;

    const MAIL_MAILER_TRANSPORT_NOT_FOUND = 500;
    const MAIL_INVALID_TRANSPORT_OPTION = 501;
    const MAIL_INVALID_TRANSPORT_INSTANCE = 502;
    const MAIL_SENDING_FAILED = 503;

    const FILESYSTEM_UNKNOWN_ERROR = 600;
    const FILESYSTEM_UPLOADED_FILE_EXCEEDS_SERVERS_MAX_UPLOAD_SIZE = 601;
    const FILESYSTEM_UPLOADED_FILE_EXCEEDS_CLIENTS_MAX_UPLOAD_SIZE = 602;
    const FILESYSTEM_FILE_ONLY_PARTIALLY_UPLOADED = 603;
    const FILESYSTEM_NO_FILE_UPLOADED = 604;
    const FILESYSTEM_MISSING_TEMPORARY_UPLOAD_DIR = 606;
    const FILESYSTEM_FAILED_TO_WRITE_TO_DISK = 607;
    const FILESYSTEM_FILE_UPLOAD_STOPPED = 608;

    const UTILS_HASHER_NOT_FOUND = 1000;
}
